import type { Metadata } from "next";
import { Quicksand, Poppins} from "next/font/google";
import "../globals.css";


const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-quicksand",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400","600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        
      <body
        className={`antialiased ${quicksand.variable} ${poppins.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
